FROM node:18-alpine
RUN apk update && apk add curl --no-cache
ENV PORT=3001
ENV ACCESS_SECRET_KEY=b/NdxwgaYrFIyJxmlbaU8FDxABPy7WjPFU7T2eMyg2g=
ENV REFRESH_SECRET_KEY=b/djasdjasjuHHHG12388HHHJDKSKDIEOEOEOOIRR=
ENV PORT_REDIS=6379
ENV HOST_REDIS=redis_server
ENV HOST_MYSQL=mysql_server
ENV WHITE_LIST="http://localhost:3000, http://www.fitfood.kd14.me, https://www.fitfood.kd14.me"
ENV IMAGE_ENDPOINT_URL=/upload/images
ENV USER_MYSQL=testuser
ENV PASSWORD_MYSQL=12345678
ENV EMAIL=tranhakhanhduy2001@gmail.com
ENV EMAIL_PASSWORD=pvyktypovblprveb

RUN apk update && apk add bash
RUN echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p

WORKDIR /app

COPY ./package.json ./yarn.lock .



RUN yarn install --frozen-lockfile --no-cache

COPY . .

CMD ["yarn", "start"]
